services:
  # MySQL 데이터베이스 서비스 설정
  backend-database:
    image: mysql:8.0
    container_name: backend-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis 서비스 설정
  backend-redis:
    image: redis:7.0
    container_name: backend-redis
    ports:
      - "26379:6379"
    networks:
      - backend-net

  # Django 애플리케이션 서비스 설정
  backend-django:
    image: backend-django
    container_name: backend-django
    build: .
    volumes:
      - .:/backend
      - ./gcp-key.json:/app/gcp-key.json # GCP veo 키 파일 마운트
    ports:
      - "28000:8000"
    depends_on:
      backend-database:
        condition: service_healthy
      backend-redis:
        condition: service_started
    env_file:
      - ./.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-key.json # voe key 컨테이너 내부 경로
    networks:
      - backend-net
      - backend-traefik
    # develop:
    #   watch:
    #     - path: .
    #       target: /backend
    #       action: sync+restart
    #     - path: ./requirements.txt
    #       target: /backend/requirements.txt
    #       action: rebuild
    labels:
      - "traefik.enable=true"
      # HTTP 라우터 설정 (리디렉션 전용)
      - "traefik.http.routers.backend-http.rule=Host(`epi-log.site`, `www.epi-log.site`)"
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.middlewares=redirect-to-https"
      # HTTPS 라우터 설정 (실제 서비스용)
      - "traefik.http.routers.backend-https.rule=Host(`epi-log.site`, `www.epi-log.site`)"
      - "traefik.http.routers.backend-https.entrypoints=websecure"
      - "traefik.http.routers.backend-https.tls=true"
      - "traefik.http.routers.backend-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      # 리디렉션 미들웨어 정의
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  # Prometheus 모니터링 서비스 설정
  backend-prometheus:
    image: prom/prometheus:v2.45.6
    container_name: backend-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.prom.rule=Host(`prometheus.epi-log.site`)"
    #   - "traefik.http.routers.prom.entrypoints=websecure"
    #   - "traefik.http.routers.prom.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.prom.loadbalancer.server.port=9090"

    ports:
      - "29090:9090"
    networks:
      - backend-net
      - backend-traefik

  # Grafana 모니터링 서비스 설정
  backend-grafana:
    image: grafana/grafana:10.4.0
    container_name: backend-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD} # Grafana 관리자 비밀번호
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # Grafana 관리자 사용자 이름
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GRAFANA_ROLE} # 익명 사용자의 역할 설정 (Admin, Editor, Viewer 중 선택 가능)
      - GF_INSTALL_PLUGINS=farski-blendstat-panel # Grafana 플러그인 설치 (예: Blendstat 패널)
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning # Grafana 프로비저닝 (설정)
      - grafana_data:/var/lib/grafana # Grafana 데이터 (대시보드 등)
    ports:
      - "23000:3000" # Grafana는 기본적으로 3000번 포트입니다
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.services.grafana.loadbalancer.server.port=3000
    #   - traefik.http.routers.grafana.entrypoints=websecure
    #   - traefik.http.routers.grafana.tls.certresolver=letsencrypt
    #   - traefik.http.routers.grafana.rule=Host(`grafana.epi-log.site`)

    networks:
      - backend-net
      - backend-traefik

# volume 설정
volumes:
  mysql_data:
  grafana_data:

# 컨테이너 네트워크 설정
networks:
  backend-net:
    driver: bridge
  backend-traefik:
    external: true # Traefik 네트워크를 외부에서 관리하도록 설정,
