# Generated by Django 4.2.23 on 2025-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_uri',
            field=models.TextField(verbose_name='GCS Video URI'),
        ),
    ]
