# Generated by Django 4.2.23 on 2025-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0003_video_character_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='narration_audio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Narration Audio URL'),
        ),
    ]
