# Generated by Django 4.2.23 on 2025-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0004_video_narration_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_combined',
            field=models.BooleanField(default=False, verbose_name='Is Combined Video'),
        ),
    ]
