# Generated by Django 4.2.23 on 2025-07-23 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veo3Video', '0004_video_narration_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_id',
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
    ]
