# Generated by Django 4.2.23 on 2025-07-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0005_remove_video_user_id_video_user'),
        ('veo3Video', '0005_video_is_combined'),
    ]

    operations = [
    ]
