# Generated by Django 4.2.23 on 2025-07-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0006_merge_20250724_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='narration_audio_url',
        ),
    ]
