# Generated by Django 5.2.4 on 2025-07-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0006_merge_20250724_1351'),
        ('veo3Video', '0007_remove_video_narration_audio_url'),
    ]

    operations = [
    ]
