# Generated by Django 5.2.4 on 2025-07-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0008_merge_20250727_0556'),
        ('veo3Video', '0008_merge_20250728_0501'),
    ]

    operations = [
    ]
