# Generated by Django 5.2.4 on 2025-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0009_merge_20250729_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
