# Generated by Django 5.2.4 on 2025-07-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veo3Video', '0010_video_is_deleted_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='Is Deleted'),
        ),
    ]
