"""
Django settings for backend_django project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

개발용 환경 설정 파일
"""

from pathlib import Path
import os
import environ

AUTH_USER_MODEL = 'users.User'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# reading .env.dev file
environ.Env.read_env(
    env_file=os.path.join(BASE_DIR, '.env.dev')
)

# False if not in os.environ because of casting above
DEBUG = env.bool("DEBUG", default=True) # 개발환경에서만 사용

# Raises Django's ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env('DJANGO_SECRET_KEY') # django 시크릿키는 env에서 관리

# 🐕 개발용
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # '34.22.81.8', # GCP VM IP
    'backend-django', # Docker 컨테이너 이름
    # 'epi-log.site', # 도메인
    # 'www.epi-log.site', # www 서브도메인
    # '13.209.163.154',         # EC2 퍼블릭 IP
    # 'epi-log.site',
    # 'www.epi-log.site',
    # '.epi-log.site',          # 서브도메인 전체 허용 (예: grafana.epi-log.site)

]


# Django 로컬 개발 환경 포트
BACKEND_DOMAIN = 'localhost:8000'


# OpenAI API 키
OPENAI_API_KEY = env('OPENAI_API_KEY')

# Runway API 키
RUNWAY_API_KEY = env('RUNWAY_API_KEY')

# GCS 관련 설정
GOOGLE_CLOUD_PROJECT_ID = env('GOOGLE_CLOUD_PROJECT_ID')
GOOGLE_CLOUD_GCS_BUCKET = env('GOOGLE_CLOUD_GCS_BUCKET')

# Application definition

INSTALLED_APPS = [
    # API 개발시 생성한 애플리케이션 명시
    'books', # Books 애플리케이션 추가
    'characters', # Characters 애플리케이션 추가

    'veo3Video',

    'users', # Users 애플리케이션 추가

    # 's3test', # S3 테스트용 앱


    'django_prometheus', # Django Prometheus 추가
    'rest_framework', # Django REST framework 추가
    'storages', # Django Storages 추가

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# env 파일에서 DB 이름, 사용자, 비밀번호를 읽어옴
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='3306'),  # 기본 MySQL 포트
        # 'OPTIONS': {
        #     'charset': 'utf8mb4', 
        # },
    }
}


# S3 기본 설정
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

# 정적 파일 설정
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"

# 미디어 파일 설정 (선택)
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"


# Caching : Redis를 임시저장소/캐시 용도로 사용
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {

    # 기본 캐시 설정
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },

    # 대본 임시저장용 캐시
    'script_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/2',  # 1~15번까지 설정 가능
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }    
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 이 부분을 꼭 추가해야 함
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Celery 설정
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='amqp://admin:1234@backend-rabbitmq:5672//')
CELERY_RESULT_BACKEND = f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'
