"""
Django settings for backend_django project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

개발용 환경 설정 파일
"""

from pathlib import Path
import os
import environ

AUTH_USER_MODEL = 'users.User'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# reading .env.dev file
environ.Env.read_env(
    env_file=os.path.join(BASE_DIR, '.env.dev')
)

# 레디스 환경 설정 호출
REDIS_HOST = env("REDIS_HOST", default="backend-redis")
REDIS_PORT = env("REDIS_PORT", default="6379")


# False if not in os.environ because of casting above
DEBUG = env.bool("DEBUG", default=True) # 개발환경에서만 사용

# Raises Django's ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env('DJANGO_SECRET_KEY') # django 시크릿키는 env에서 관리

# 🐕 개발용
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'backend-django', # Docker 컨테이너 이름
]

# Swagger 페이지는 인증 필터에 걸리지 않음 (JWT 환경에서는 대부분 불필요)
SWAGGER_EXEMPT_URLS = [
    '/swagger/',
    '/redoc/',
    '/swagger.json',
    '/swagger.yaml',
    '/metrics',          # Prometheus
    '/static/',          # 정적 파일
    '/users/login/',     # JWT 로그인 API
    '/users/signup/',    # JWT 회원가입 API
    '/users/token/refresh/', # JWT 토큰 갱신 API
    # 다른 API들은 JWT 인증 필요
    # '/books/',           # books 관련 url은 통과
    # '/characters/',      # characters 관련 url은 통과 (오타 수정)
    # '/narration/',       # narration 관련 url은 통과
    # '/veo3Video/',       # voe3Video 관련 url은 통과
]

# 로그인 URL 설정 (JWT 환경에서는 불필요)
# LOGIN_URL = '/users/login/'



# Django 로컬 개발 환경 포트
BACKEND_DOMAIN = 'localhost:8000'


# OpenAI API 키
OPENAI_API_KEY = env('OPENAI_API_KEY')

# Gemini API 키
GEMINI_API_KEY = env('GEMINI_API_KEY')

# Runway API 키
RUNWAY_API_KEY = env('RUNWAY_API_KEY')

# GCS 관련 설정
GOOGLE_CLOUD_PROJECT_ID = env('GOOGLE_CLOUD_PROJECT_ID')
GOOGLE_CLOUD_GCS_BUCKET = env('GOOGLE_CLOUD_GCS_BUCKET')

# Application definition

INSTALLED_APPS = [
    # API 개발시 생성한 애플리케이션 명시
    'books', # Books 애플리케이션 추가
    'characters', # Characters 애플리케이션 추가
    'veo3Video',
    'users', # Users 애플리케이션 추가

    'django_prometheus', # Django Prometheus 추가
    'rest_framework', # Django REST framework 추가
    'rest_framework_simplejwt', # JWT 인증 추가
    'rest_framework_simplejwt.token_blacklist', # JWT 토큰 블랙리스트 추가
    'storages', # Django Storages 추가
    'drf_yasg', # Django REST framework Swagger 추가
    'corsheaders', # CORS 허용 허락

    'django_eventstream', # SSE 실시간 알림
    'channels', # Django Channels 추가

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django_grip.GripMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'config.middleware.LoginRequiredMiddleware', # JWT 환경에서는 비활성화
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware'
]

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_URL='static/'

CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# env 파일에서 DB 이름, 사용자, 비밀번호를 읽어옴
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='3306'),  # 기본 MySQL 포트
        # 'OPTIONS': {
        #     'charset': 'utf8mb4', 
        # },
    }
}


# S3 기본 설정
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

# 정적 파일 설정 (개발환경에서는 로컬 서빙)
# STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"  # 개발환경에서는 비활성화
# STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"  # 개발환경에서는 비활성화

# 미디어 파일 설정 (사용자 업로드 파일은 S3 사용)
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"


# Caching : Redis를 임시저장소/캐시 용도로 사용
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {

    # 기본 캐시 설정 - Celery 작업 결과물 저장
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/0',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },

    # 대본 임시저장용 캐시
    'script_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/2',  # 1~15번까지 설정 가능
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }    
    }
}

# Django EventStream 제거 - 직접 SSE 구현 사용
# 이제 Redis pub/sub을 직접 사용하여 SSE 구현
print(f"🔍 [SETTINGS] Django EventStream 제거됨 - 직접 SSE 구현 사용")


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
             "hosts": [f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/3'],
        },
    },
}



# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": f"amqp://{env('RABBITMQ_USER', default='guest')}:{env('RABBITMQ_PASSWORD', default='guest')}@backend-rabbitmq:5672",
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 이 부분을 꼭 추가해야 함
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# GRIP 설정 (django-eventstream 필요)
GRIP_URL = 'http://localhost:5561'

# Celery 설정
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='amqp://admin:1234@backend-rabbitmq:5672//')
CELERY_RESULT_BACKEND = f"redis://{env('REDIS_HOST', default='backend-redis')}:{env('REDIS_PORT', default='6379')}/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# 개발 환경에서도 실제 비동기 처리 테스트를 위해 EAGER 모드 비활성화
# 디버깅 시에만 필요하면 주석 해제
# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_TASK_EAGER_PROPAGATES_EXCEPTIONS = True


# Django REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Simple JWT 설정 (개발용 - 환경변수로 관리)
from datetime import timedelta

SIMPLE_JWT = {
    # 토큰 수명 (환경변수로 관리)
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=env.int('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', default=3600)  # 개발: 60분 (개발 편의성)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=env.int('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=7)  # 개발: 7일 (개발 편의성)
    ),

    # 토큰 정책 (환경변수로 관리)
    'ROTATE_REFRESH_TOKENS': env.bool('JWT_ROTATE_REFRESH_TOKENS', default=True),
    'BLACKLIST_AFTER_ROTATION': env.bool('JWT_BLACKLIST_AFTER_ROTATION', default=True),
    'UPDATE_LAST_LOGIN': env.bool('JWT_UPDATE_LAST_LOGIN', default=True),

    # 보안 설정 (환경변수로 관리)
    'ALGORITHM': env('JWT_ALGORITHM', default='HS256'),
    'SIGNING_KEY': env('JWT_SECRET_KEY', default=SECRET_KEY),  # JWT 전용 키 또는 Django 키 fallback
    'VERIFYING_KEY': None,
    'AUDIENCE': env('JWT_AUDIENCE', default=None),  # 토큰 수신자
    'ISSUER': env('JWT_ISSUER', default=None),      # 토큰 발급자

    # 헤더 설정
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    # 토큰 클래스 설정
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

# Swagger 설정 (JWT 인증 자동 인식)
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Bearer 토큰을 입력하세요. 예: Bearer eyJ0eXAiOiJKV1Q...'
        }
    },
    'USE_SESSION_AUTH': False,  # 세션 인증 비활성화
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'example'
}


