# settings_prod.py
"""
Django settings for backend_django project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ

AUTH_USER_MODEL = 'users.User'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# reading .env file
environ.Env.read_env(
    env_file=os.path.join(BASE_DIR, '.env')
)

# False if not in os.environ because of casting above
DEBUG = env.bool("DEBUG", default=True) # 개발환경에서만 사용

# Raises Django's ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env('DJANGO_SECRET_KEY') # django 시크릿키는 env에서 관리


# ⭐️ 부하테스트용 - 모든 호스트 허용
ALLOWED_HOSTS = ["*"]  # 부하테스트용 임시 설정
# ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")  # 원래 설정

# ⭐️ 배포용
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 배포 서버
BACKEND_DOMAIN = 'epi-log.site'

# CORS 설정 (배포용)
CORS_ALLOWED_ORIGINS = [
    "https://epi-log.site",
    "http://epi-log.site",
    "https://www.epi-log.site",
    "http://www.epi-log.site",
    "https://epi-log.vercel.app",
]

# 개발/테스트용 (Postman, 로컬 클라이언트 등)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.epi-log\.site$",
    r"^http://.*\.epi-log\.site$",
    r"^https?://epi-log-.*\.vercel\.app$",
]

# 추가 허용 오리진 (필요시)
# CORS_ALLOWED_ORIGINS += [
#     "http://localhost:3000",    # React 개발 서버
#     "http://127.0.0.1:3000",   # 로컬 프론트엔드
# ]

# CORS 헤더 설정
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # 보안: 특정 도메인만 허용

# CORS 허용 헤더 (JWT 토큰 전송용)
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken',
    'x-requested-with',
    'x-password',
    'accept',
    'origin',
    'user-agent',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

# CSRF 신뢰할 수 있는 출처 설정
CSRF_TRUSTED_ORIGINS = [
    "https://epi-log.site",
    "http://epi-log.site", 
    "https://www.epi-log.site",
    "http://www.epi-log.site",
    "https://epi-log.vercel.app",
]

# 참고: Django REST Framework의 APIView는 자동으로 csrf_exempt 적용됨
# JWT 기반 API에서는 별도 CSRF 설정 불필요

# 배포용/(근데 실제로 사용은 안했음.)
SECURE_SSL_REDIRECT = True
SECURE_REDIRECT_EXEMPT = [r'^metrics/?$']  # /metrics 경로는 HTTPS 리다이렉트 제외
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# OpenAI API 키
# OPENAI_API_KEY = env('OPENAI_API_KEY')

# Gemini API 키
GEMINI_API_KEY = env('GEMINI_API_KEY')

# Runway API 키
# RUNWAY_API_KEY = env('RUNWAY_API_KEY')

# GCS 관련 설정
# GOOGLE_CLOUD_PROJECT_ID = env('GOOGLE_CLOUD_PROJECT_ID')
# GOOGLE_CLOUD_GCS_BUCKET = env('GOOGLE_CLOUD_GCS_BUCKET')

# Application definition

INSTALLED_APPS = [
    # API 개발시 생성한 애플리케이션 명시
    'books', # Books 애플리케이션 추가
    'characters', # Characters 애플리케이션 추가

    # 'videos2',
    # 'veo3Video',

    'users', # Users 애플리케이션 추가
    # 'narration', # Narration 애플리케이션 추가

    # 's3test', # S3 테스트용 앱


    'django_prometheus', # Django Prometheus 추가
    'rest_framework', # Django REST framework 추가
    'storages', # Django Storages 추가
    'rest_framework_simplejwt', # JWT 인증 추가
    'rest_framework_simplejwt.token_blacklist', # JWT 토큰 블랙리스트 추가
    'drf_yasg', # Django REST framework Swagger 추가
    'corsheaders', # CORS 허용 허락

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 미들웨어 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# env 파일에서 DB 이름, 사용자, 비밀번호를 읽어옴
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='3306'),  # 기본 MySQL 포트
    }
}


# S3 기본 설정
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

# 정적 파일 설정
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"

# 미디어 파일 설정 (선택)
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"


# Caching : Redis를 임시저장소/캐시 용도로 사용
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {

    # 기본 캐시 설정
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },

    # 대본 임시저장용 캐시
    'script_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/2',  # 1~15번까지 설정 가능
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }    
    }
}

# Django EventStream 제거 - 직접 SSE 구현 사용
# 이제 Redis pub/sub을 직접 사용하여 SSE 구현
print(f"🔍 [SETTINGS] Django EventStream 제거됨 - 직접 SSE 구현 사용")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
             "hosts": [f'redis://{env("REDIS_HOST", default="backend-redis")}:{env("REDIS_PORT", default="6379")}/0'],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 이 부분을 꼭 추가해야 함
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Celery 설정 (비동기 처리를 위한 필수 설정)
CELERY_BROKER_URL = env('CELERY_BROKER_URL')  # 환경 변수에서 가져옴
CELERY_RESULT_BACKEND = f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}/0"  # 환경 변수에서 가져옴
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# Django REST Framework 설정 (배포용)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Simple JWT 설정 (배포용 - 환경변수로 관리)
from datetime import timedelta

SIMPLE_JWT = {
    # 토큰 수명 (환경변수로 관리)
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=env.int('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', default=60)  # 프로덕션: 60분 (보안 강화)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=env.int('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=1)  # 프로덕션: 1일 (보안 강화)
    ),
    
    # 토큰 정책 (환경변수로 관리)
    'ROTATE_REFRESH_TOKENS': env.bool('JWT_ROTATE_REFRESH_TOKENS', default=True),
    'BLACKLIST_AFTER_ROTATION': env.bool('JWT_BLACKLIST_AFTER_ROTATION', default=True),
    'UPDATE_LAST_LOGIN': env.bool('JWT_UPDATE_LAST_LOGIN', default=True),
    
    # 보안 설정 (환경변수로 관리)
    'ALGORITHM': env('JWT_ALGORITHM', default='HS256'),
    'SIGNING_KEY': env('JWT_SECRET_KEY', default=SECRET_KEY),  # JWT 전용 키 또는 Django 키 fallback
    'VERIFYING_KEY': None,
    'AUDIENCE': env('JWT_AUDIENCE', default=None),  # 토큰 수신자
    'ISSUER': env('JWT_ISSUER', default=None),      # 토큰 발급자
    
    # 헤더 설정
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    "AUTH_COOKIE_ACCESS": "access",
    "AUTH_COOKIE_REFRESH": "refresh",
    "AUTH_COOKIE_SAMESITE": "Lax",
    "AUTH_COOKIE_SECURE": True,     # 운영이면 True 필수
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_DOMAIN": "epi-log.site",
    "AUTH_COOKIE_ACCESS_MAX_AGE": 60 * 60 * 24,
    "AUTH_COOKIE_REFRESH_MAX_AGE": 60 * 60 * 24 * 7,
    
    # 토큰 클래스 설정
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
}
