# Generated by Django 4.2.23 on 2025-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_uri', models.URLField(max_length=500, unique=True, verbose_name='GCS Video URI')),
                ('prompt', models.TextField(verbose_name='Video Generation Prompt')),
                ('title', models.CharField(max_length=255, verbose_name='Video Title')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='User ID (from JWT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Timestamp')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
