# Generated by Django 4.2.23 on 2025-07-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('voe3Video', '0002_alter_video_video_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='characters.character'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
