# ⭐️ 배포용
services:
  traefik:
    image: traefik:v2.9
    container_name: backend-traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--entrypoints.websecure.address=:443" # 중요 - Traefik이 HTTPS 요청을 수신할 포트 443을 열음
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" # 중요 - HTTP 요청을 HTTPS로 리다이렉트
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https" # 중요 => HTTPS 강제 적용
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true" # 중요 - Let's Encrypt를 사용하여 TLS 인증서를 자동으로 발급받음
      - "--certificatesresolvers.letsencrypt.acme.email=dnjsgml0578@gmail.com" # 중요 - 인증 관련 알림을 받을때 필요, Let's Encrypt에 자동으로 등록됨
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json" # 중요 - 인증서 저장 위치, 해당 경로를 볼륨에 마운팅하여 영구 저장됨
    ports:
      - "80:80"
      - "443:443" # 중요
      - "8090:8090" # Traefik 대시보드 포트
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/letsencrypt # 중요
    networks:
      - backend-traefik # Traefik 네트워크를 외부에서 관리하도록

volumes:
  traefik-certificates: # 중요

networks:
  backend-traefik:
    external: true # Traefik 네트워크를 외부에서 관리하도록 설정, backend_django/docker-compose.yml에서 사용하기 위함
