# Generated by Django 4.2.23 on 2025-07-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_description_book_pdf_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': '책', 'verbose_name_plural': '책들'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
