# Generated by Django 4.2.23 on 2025-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('PROCESSING', '처리 중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', help_text='PDF 처리 상태', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
